### ISSUE TITLE
Kerberos Authentication Windows/Linux

### ISSUE THREAD

**Issue by ittchmh** [Badgerati/Pode#819] opened 2021-09-12 16:28 UTC
### Describe the Feature
Kerberos Authentication Windows/Linux

### Related Issues

- Current implementation allows Kerberos Authentication using Pode deployment on IIS Server only
- Doesn't work on Linux

### Additional Context
There is a very good library for .NET https://github.com/dotnet/Kerberos.NET
Examples https://github.com/dotnet/Kerberos.NET/tree/develop/Samples

**Comment by RobinBeismann** [comment] 2021-09-12 16:32
This is somewhat a duplicate of #402 whichs topic is Kerberos/NTLM already.
Maybe you could add your content there?

**Comment by Badgerati** [comment] 2021-09-13 19:29
Agreed this would be better in #402.

That said, I've not come across Kerberos.NET before and it looks like it could do what we need! I'll have to try it out 😮

**Closed** 2022-01-02 16:54 UTC
Labels: feature :sunny:
