### ISSUE TITLE
Get-PodeAuthMiddleware  does not always return the entire auth object

### ISSUE THREAD

**Issue by jhainau** [Badgerati/Pode#576] opened 2020-05-26 22:26 UTC
This may be due to me not using the auth functions in the intended manner, but, it does work correctly the first time that it is called but then will only randomly work afterwards. In my setup, I have the following in my server script block: ( removed some portions for brevity)

```
param (
    [int]$Port = 443
)

Import-Module Pode
Import-Module ActiveDirectory

# create a server, and start listening on port 8085
Start-PodeServer -Threads 5 -Name "CustomApi" -ScriptBlock {
New-PodeAuthType -Basic | Add-PodeAuth -Name 'Login' -ScriptBlock {
    param($username, $password)
    $SecPassword = ConvertTo-SecureString -String $password -AsPlainText -Force
    $userCred = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $username, $SecPassword

    $test = $(try { Get-ADUser -Properties memberof,SID,SamAccountName,UserPrincipalName -Identity $username -Credential $userCred -ErrorAction Stop }Catch { $false })

    if ($test -ne $false) {
        return @{ User = [ordered]@{
                'ID'       = $test.SID
                'Name'     = $test.SamAccountName
                'UPN'      = $test.UserPrincipalName
                'AdGroups' = $test.memberof
                'cred'     = $userCred
            }
        }
    }
    return $null
} 


$o365Routes = Get-ChildItem -file  -Path "C:\CustomRestAPI\O365"
foreach ($o365Route in $o365Routes){
    Add-PodeRoute -Method Get -Path "/o365/$([io.path]::GetFileNameWithoutExtension( $o365Route))"  -Middleware (Get-PodeAuthMiddleware -Name 'Login' -Sessionless )  -FilePath "./O365/$o365Route" -PassThru
}
}
```
the portion of concern is that the "AdGroups' and "cred" don't always make it to the route so it will assume that the person is not a member of the appropriate AD Group, or when it reuses the credential for some of the other services, (we have a password sync tool, so the userName is predictable and the passwords are the same) it will fail due to not having a valid credential object.  

As I mentioned above, the issue only occurs after the first rest call, then after that, it is only randomly successful...

This is on an internal server that is not accessible from outside my org domain and not available to anyone not in my org AD realm.

In the route, I check for group membership for specific groups (for the ones listed above, the user has to be an Exchange Admin) but when it is in the failing state, I notice that nothing is being returned by the Auth middleware for the "AdGroups" portion of the Auth object.

**Comment by jhainau** [comment] 2020-05-26 22:29
by the way, I have to use windows PowerShell since there is not currently any support for the V0.4578.0   ExchangeOnlineManagement cmdlets in PowerShell Core.

**Comment by Badgerati** [comment] 2020-05-27 08:08
Hey @jhainau,

I believe somebody here once had a similar issue; if you add `Import-PodeModule -Name ActiveDirectory` at the top in your `Start-PodeServer` scriptblock, does that resolve the problem?

```powershell
Start-PodeServer {
    Import-PodeModule -Name ActiveDirectory
}
```

The issue is that `Get-ADUser` does "work" without the AD module, but sometimes it doesn't retrieve everything. Using `Import-PodeModule` will load the AD module into all runspaces for Pode, and allows `Get-ADUser` to work normally.

**Comment by jhainau** [comment] 2020-05-27 15:24
My apologies, I did remember reading something about it a while ago, but couldn't find the info when I looked this time. 
This does appear to fix my issue (once I placed the line in the correct location :-) )

**Comment by Badgerati** [comment] 2020-05-28 16:50
Excellent! I'll close the issue, but if you still have troubles feel free to reopen! :)

**Closed by Badgerati** 2020-05-28 16:50 UTC
